### ISSUE TITLE
[主線] [PTT] 增加基本註解

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#109]
### 實作細節 / Details of Implement
現有大部分的 code 皆未有註解，須對 function 跟 test 增加註解

### 期程 / Schedule
- 討論時間： 一天
- 實作時間： 一天
- 確認時間： 一天

### 相關文件 / Documents
實作中

### 相關項目 / Child Task

- [x] route_users.go , route_users_test.go , route_users_mock_test.go #110 
- [x] route_token.go , route_token_test.go , route_token_mock_test.go #173 
- [ ] route_classes.go , route_classes_test.go , route_classes_mock_test.go #174 
- [x] route_boards.go, route_boards_test.go , route_boards_mock_test.go #175 
- [ ] route_boards_articles.go , route_boards_articles_test.go #176

**Comment by PichuChen** [comment]
這樣好像 ISSUE 會太大，如果先把需要註解的檔案都先表列出來讓每個檔案都分成子 ISSUE 下去處理呢？

**Comment by y2468101216** [comment]
要拆分，我還在整理，目前先開著方便我作整理

**Comment by PichuChen** [comment]
應該可以把它拆成每個檔案一個項目然後讓大家認領，不過現在有些東西要先處理，主要是註解的格式還有需要註解的範圍，例如沒有 exported 的 method 需不需要註解

**Comment by PichuChen** [comment]
然後需要在 ISSUE 的開頭有個註解的範例，這樣大家才知道要怎麼寫成相同的風格。

**Comment by y2468101216** [comment]
恩，所以我先弄了一個 pr 出來讓大家參考，等好了以後會指派子 issue 給大家

**Comment by PichuChen** [comment]
這個 ISSUE 目前還有在更新嗎？ 不然兩週後要把他先關掉了喔？

**Comment by PichuChen** [comment]
重新檢查這張 umbrella issue 的 child tasks：原先清單中未完成的 #174（route_classes）與 #176（route_boards_articles）都已在 2021-07-15 以 completed 關閉；其他列出的項目也已完成。

因此這張主線 issue 已沒有未完成 child task，以 **completed** 關閉。
