### ISSUE TITLE
[建議] 增加測試

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#36]
### 原本作法的問題 / Existed Problem
目前部分 api 沒有測試
此 issue 會隨著專案增加新 api 而改變

### 實作細節 / Details of Implement
參考原有的 route_user_test.go 下去寫

### 期程 / Schedule

- [x] route_boards_treasures_test.go :  未指派  #73 
- [x] route_borads_test.go : 進行中 #70
- [x] route_borads_articles_test.go : 未指派 #74 
- [x] route_classes_test.go : 完成，#57
- [x] route_token_test.go : 完成，pr 審核中 #37 

### 相關文件 / Documents
參考官方文件

**Comment by PichuChen** [comment]
> ### 原本作法的問題 / Existed Problem
> 目前部分 api 沒有測試
> 
> ### 實作細節 / Details of Implement
> 參考原有的 route_user_test.go 下去寫
> 
> ### 期程 / Schedule
> 作完了 route_token_test.go
> 但是需要測試帳密
> 
> ### 相關文件 / Documents
> 參考官方文件

測試資料的帳號密碼可以透過 Slack 詢問

**Comment by PichuChen** [comment]
目前我已經把一些測試檔案放上去了，接下來應該會先新增一個 feature/testing branch 然後讓大家把東西先推過去？

**Comment by PHChenGit** [comment]
我可以幫忙

**Comment by PichuChen** [comment]
> 我可以幫忙

如果要幫忙的話可以先開子ISSUE, 看你要先弄哪個檔案這樣？

**Comment by PHChenGit** [comment]
> > 我可以幫忙
> 
> 如果要幫忙的話可以先開子ISSUE, 看你要先弄哪個檔案這樣？

實作 route_borads_test.go
已開 Issue #55

**Comment by DeanXu2357** [comment]
我希望實作 #74  請指派給我

**Comment by y2468101216** [comment]
目前皆已完成
